name: laos-climate-change
channels:
  - conda-forge

dependencies:
  - python=3.12

  # Science
  - numpy
  - scipy
  - jax

  # Data
  - pandas
  - openpyxl
  - xlrd
  - pandas-datareader

  # Graphics
  - matplotlib
  - seaborn

  # Bayes
  - pymc>=5.21.1
  - pytensor>=2.28.3
  - arviz
  - preliz
  - pymc-extras
  - nutpie>=0.14.2

  # Not Bayes
  - scikit-learn
  - statsmodels

  # Geospatial
  - geopandas
  - pysal
  - geopy

  # Etc
  - notebook<7
  - openai
  - wikipedia
  - pyprojroot
  - wbdata

  # Testing
  - pytest
  - pytest-cov
  - pre-commit
  - pip

  - pip:
      - git+https://github.com/aseyboldt/nutpie.git@transforms
      - git+https://github.com/aseyboldt/flowjax.git@add-mvscale
  - pip:
      - flowjax
      - corner
