name: laos-climate-change
channels:
  - conda-forge

dependencies:
  - python=3.12

  # Science
  - numpy
  - scipy

  # Data
  - pandas
  - openpyxl
  - xlrd
  - pandas-datareader

  # Graphics
  - matplotlib
  - seaborn

  # Bayes
  - pymc
  - pytensor
  - arviz
  - preliz
  - pymc-extras
  - nutpie

  # Not Bayes
  - scikit-learn
  - statsmodels

  # Geospatial
  - geopandas
  - pysal

  # Etc
  - notebook<7

  # Testing
  - pytest
  - pytest-cov
  - pre-commit
  - pip

  - pip:
      - git+https://github.com/aseyboldt/nutpie.git@transforms
      - git+https://github.com/aseyboldt/flowjax.git@add-mvscale
