= Literature review

== CO#sub[2], climate change and disasters
Over the past few decades, mounting scientific evidence has established a link between anthropogenic CO#sub[2] emissions, global warming, and the increasing frequency and severity of natural disasters worldwide. Much of this evidence has been synthesized by the Intergovernmental Panel on Climate Change (IPCC), a scientific body formally mandated to assess climate change based on the latest scientific, technical, and socio-economic information. The IPCC's comprehensive assessments, including the Sixth Assessment Report  #cite(<ipcc_ar6>, form:"prose") and earlier publications, demonstrate how greenhouse gas (GHG) emissions, primarily from fossil fuel combustion, have driven unprecedented atmospheric temperature increases @IPCC_AR6_WGI_2021, @IPCC_AR6_WGII_2022, @IPCC_AR6_WGIII_2022. These temperature changes, in turn, have intensified climate-related hazards, including heatwaves, storms, floods, and droughts, all of which pose growing risks to human societies and ecosystems.

The existing literature indicates a clear causal relationship between CO#sub[2] emissions and global warming, a phenomenon well-documented in the Physical Science Basis of the AR6 @IPCC_AR6_WGI_2021. Global surface temperatures have risen by approximately 1.1°C above pre-industrial levels, with CO#sub[2] identified as the dominant driver. This warming alters the Earth's energy balance, accelerates ice melt, disrupts precipitation patterns, and amplifies the intensity of extreme weather events. The Special Report on Emissions Scenarios @ipcc lay the groundwork for understanding how different future emission trajectories could lead to distinct climate outcomes, emphasizing the role of mitigation in curbing long-term disaster risks.

Building on this scientific foundation, the AR6 Working Group II Report @IPCC_AR6_WGII_2022 highlights the growing vulnerability of human and natural systems to climate-related disasters. The report details how warming has increased the exposure of populations and infrastructure to climate hazards and stresses the compounding nature of these risks, especially in low-income regions. It also notes that socioeconomic disparities influence adaptive capacity, exacerbating disaster impacts in vulnerable communities. The way in which climate change has amplified the frequency and magnitude of natural disasters has also been documented be multiple scientific and institutional findings as indicated by @vanaalst2006impacts.


Finally, the AR6 Working Group III Report @IPCC_AR6_WGII_2022 underlines the direct link between CO#sub[2] and global warming. The report provides evidence that immediate and sustained emission reductions across all sectors are essential to staying below the 1.5°C or even 2°C warming thresholds established under the Paris Agreement. Delaying mitigation efforts increases the likelihood of irreversible climate tipping points, such as permafrost thawing or coral reef collapse, which could further exacerbate natural disasters. The mitigation strategies discussed include a transition to low-carbon energy, reforestation, and carbon capture technologies.

Attributing disaster damage to climate change remains complex. Bouwer @bouwer2011have critically examine trends in economic losses and finds that much of the observed increase can be explained by rising exposure—such as more people and infrastructure in vulnerable areas—rather than a clear signal from climate change alone. This work underscores the difficulty of isolating climate-driven changes in risk from socioeconomic factors as a persistent challenge.


 == Modeling natural disasters and damage

Numerous efforts have been developed by climate scientists to develop accurate predictions of extreme weather events independently of their economic consequences. Since this paper focuses on economic impacts, we emphasize literature addressing this aspect, of the research problem.

An important focus of past research has been the development and application of Integrated Assessment Models (IAMs). However, it is important to note that IAMs often lack key components. Most notably, they do not incorporate a geospatial representation of disasters, which is central to the present research. For this reason, we adopt a different modeling approach better suited to addressing this gap.

In his Nobel Prize lecture William Nordhaus argues that climate change is the ultimate challenge for economics as an academic discipline, and asserts that "_projecting impacts is the most difficult task and has the greatest uncertainties of all the processes associated with global warming_" @nordhaus2019climate. He also provides a clear guide through past efforts undertaken by the discipline of economics to understand and model the economic impacts of climate change.

#cite(<nordhaus2019climate>, form:"prose") emphasizes the importance of models able to integrate different systems that are deeply integrated in the real world, but that are approached with a segmented perspective by different academic disciplines. In this sense, Nordhaus recognizes the relevant role of Integrated Assessment Models (IAMS) as the powerhouse tool for economic modeling of climate change.

#cite(<Botzen2019>, form:"prose") develop a valuable literature review about the state of the art. One of their findings is that empirical studies on the economic impacts of natural disasters rely heavily on various data sources, with the Emergency Events Database (EM-DAT) @cred_emdat_2024 being the most commonly used. Compiled by the Centre for Research on the Epidemiology of Disasters (CRED), EM-DAT provides extensive data on natural disasters, although it has limitations such as variable thresholds for event inclusion and potential inflation of damage estimates. According to the authors, other databases like NatCatSERVICE and Sigma, created by reinsurance companies, are less frequently used due to their limited public availability. Recent studies have shifted towards using geophysical or meteorological variables to define natural disasters. These physical indicators provide a more objective basis for assessing the economic impacts of disasters.


#cite(<Kahn2005>, form: "prose") takes an innovative approach by modeling disasters frequency and impacts as a function of different economic, institutional, and, development indicators. He explores the factors influencing the death toll from natural disasters across various nations. Using a comprehensive dataset on annual deaths from disasters in 57 countries from 1980 to 2002, #cite(<Kahn2005>, form: "prose") tests several hypotheses regarding the impact of national income, geography, and institutional quality on disaster fatalities. The study reveals that while richer nations do not experience fewer natural disaster events than poorer nations, they do suffer significantly fewer deaths from these events. This suggests that economic development provides a form of implicit insurance against the adverse effects of natural disasters. Additionally, the paper finds that democracies and nations with higher quality institutions tend to have lower death tolls from natural disasters, highlighting the importance of governance and institutional frameworks in mitigating disaster impacts.

The analysis in #cite(<Kahn2005>, form: "prose") utilizes both probit models and zero-inflated negative binomial regressions to examine the determinants of disaster fatalities. To identify the causal effect of geography on disaster fatalities, the study addresses potential confounding from national population density and institutional quality. By conditioning on democracy levels and income inequality, it isolates the specific role of geographic location. The analysis finds that geographic factors significantly influence death tolls. It also concludes that nations in Asia and the Americas experiencing higher fatalities relative to Africa. Furthermore, the paper underscores the critical role of institutional quality in insulating populations from the devastating effects of natural disasters.

#cite(<lopez_climate_2015>, form: "prose") offer a different perspective. They model the frequency of climate change related disasters as a function of country-level development indicators and global climate variables. The use a generalized linear model (GLM) to model the latent probability of a disaster with a set of country level covariates. Their approach does not consider the feedback dynamics included in IAMs models. Nevertheless, they provide a direct approach for linking climate variables, economic circumstances, and disasters.

#cite(<Howard2017>, form: "prose") perform a complete meta-analysis on the topic of global climate damage estimates to better understand the relationship between temperature changes and climate damages. They identify and address several biases present in previous meta-analyses, including duplicate estimates, omitted variables, measurement errors, overreliance on published estimates, dependent errors, and heteroskedasticity. They conclude that previous meta-analyses suffered from significant biases that flattened the relationship between temperature and climate damages. The authors find strong evidence that duplicate and omitted variable biases significantly impact the estimated temperature-damage relationship. Specifically, the magnitude of the bias depends on the treatment of speculative high-temperature damage estimates. When the authors replace the DICE-2013R damage function with an adjusted estimate, they find a three- to four-fold increase in the 2015 Social Cost of Carbon (SCC) relative to the DICE model, depending on the treatment of productivity. When catastrophic impacts are also factored in, the SCC increases by four- to five-fold. This suggests that previous estimates of climate damages and the SCC may have been significantly underestimated due to biases in the data and methodologies used.

In conclusion, the literature in this field has grown steadily over the past two decades, but challenges still remain. The integration of granular, geospatial approaches with broader macro perspectives remains limited. Despite the advantages of adopting a probabilistic perspective to better understand disasters and their associated damages, the application of Bayesian methods remains relatively uncommon. It is along these two fronts that we believe our contribution is most relevant.
